routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TagController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\GuestController;
use App\Http\Controllers\SubTagController;

/* |-------------------------------------------------------------------------- | Web Routes |-------------------------------------------------------------------------- | | Here is where you can register web routes for your application. These | routes are loaded by the RouteServiceProvider within a group which | contains the "web" middleware group. Now create something great! | */

Route::get('/', [GuestController::class , 'index'])->name('guest.dashboard');
Route::get('/show/{id}', [GuestController::class , 'show'])->name('guest.posts.show');

Route::get('/dashboard', [PostController::class , 'index'])->middleware(['auth'])->name('dashboard');
Route::get('/posts/create', [PostController::class , 'create'])->name('posts.create')->middleware(['auth']);
Route::post('/posts/create', [PostController::class , 'store'])->name('posts.store')->middleware(['auth']);
Route::post('/posts/update', [PostController::class , 'update'])->name('posts.update')->middleware(['auth']);
Route::get('/posts/destroy/{post}', [PostController::class , 'destroy'])->name('posts.destroy')->middleware(['auth']);
Route::get('/posts/edit/{id}', [PostController::class , 'edit'])->name('posts.edit')->middleware(['auth']);
Route::get('/posts/{id}', [PostController::class , 'show'])->name('posts.show')->middleware(['auth']);

Route::get('/tags', [TagController::class , 'index'])->name('tag_dashboard')->middleware(['auth']);
Route::get('/tags/create', [TagController::class , 'create'])->name('tags.create')->middleware(['auth']);
Route::post('/tags/create', [TagController::class , 'store'])->name('tags.store')->middleware(['auth']);
Route::post('/tags/update', [TagController::class , 'update'])->name('tags.update')->middleware(['auth']);
Route::get('/tags/destroy/{tag}', [TagController::class , 'destroy'])->name('tags.destroy')->middleware(['auth']);
Route::get('/tags/edit/{id}', [TagController::class , 'edit'])->name('tags.edit')->middleware(['auth']);
Route::get('/tags/{id}', [TagController::class , 'show'])->name('tags.show')->middleware(['auth']);

Route::get('/subtags', [SubTagController::class , 'index'])->name('subtags.dashboard')->middleware(['auth']);
Route::get('/subtags/create/{tagId}', [SubTagController::class , 'create'])->name('subtags.create')->middleware(['auth']);
Route::post('/subtags/create', [SubTagController::class , 'store'])->name('subtags.store')->middleware(['auth']);
Route::post('/subtags/update', [SubTagController::class , 'update'])->name('subtags.update')->middleware(['auth']);
Route::get('/subtags/destroy/{id}/{tag_id}', [SubTagController::class , 'destroy'])->name('subtags.destroy')->middleware(['auth']);
Route::get('/subtags/edit/{id}/{tag_id}', [SubTagController::class , 'edit'])->name('subtags.edit')->middleware(['auth']);

require __DIR__ . '/auth.php';

app/Http/Controllers/GuestController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tag;
use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class GuestController extends Controller
{
    public function index(Request $request)
    {
        $posts = $this->filter($request);
        $tags = Tag::all();
        return view('guests/guest_dashboard', compact('posts', 'tags'));
    }

    public function filter(Request $request)
    {
        $tag_id = $request['filter'];
        if($tag_id == null) {
            $posts = Post::all();
        } else {
            $posts = Post::when($tag_id, function($query, $tag_id) {
                $query->where('tag_id', $tag_id);
            })->get();
        }
        return $posts;
    }

    public function show($id)
    {
        // $post = Post::with('tag')->where('id', $id)->get();
        $post = Post::findOrFail($id);
        return view('/guests/show', compact('post'));
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/guests/guest_dashboard.blade.php
<x-guest-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Articles') }}
        </h2>
    </x-slot>

    <div class="flex items-center flex-col">
        <div class="flex flex-row">
            <form method="GET" action="{{ route('guest.dashboard') }}" enctype="multipart/form-data">
                @csrf
                <select name="filter" id="filtre">
                    <option value="">Sélectionner un filtre</option>
                    @foreach ($tags as $tag)
                        <option value="{{ $tag['id'] }}">{{ $tag['name'] }}</option>
                    @endforeach
                </select>
                @error('filter')
                    <div>{{ $message }}</div>
                @enderror
                <button type="submit"
                    class="m-6 bg-gray-200 border-b-2 border-gray-700 rounded-full py-2 px-4">Filtrer</button>
            </form>
        </div>

        @if ($posts)
            <div class="flex flex-row flex-wrap justify-start mt-8 gap-8 w-[90%]">
                @foreach ($posts as $post)
                    {{-- <div class="event_date"></div> --}}
                    <div
                        class="event w-80 h-72 rounded-lg p-4 bg-white flex flex-col place-content-between	border-2 border-slate-600">
                        <div class="w-fit bg-red-800 text-white rounded-full self-end font-ubuntu antialiased">
                            <span class="py-0.5 px-2">{{ $post->tag->name }}</span>
                        </div>
                        <div>
                            <a href="{{ route('guest.posts.show', ['id' => $post->id]) }}" title="Lire l'article"
                                class="w-40 title break-words font-ubuntu text-2xl">{{ $post->title }}</a>
                        </div>
                        {{-- <p class="event_time"></p> --}}
                        {{-- <p class="event_location"></p> --}}
                    </div>
                @endforeach
            </div>
        @endif
    </div>
</x-guest-layout>

resources/views/guests/show.blade.php
<x-guest-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ $post['title'] }}
        </h2>
    </x-slot>

    <div class="flex flex-row gap-4 m-4 justify-center">
        <div class="w-fit h-fit max-w-[30%] max-h-[30%] border-2 border-gray-500">
            <img src="{{ asset('storage/' . $post['picture']) }}" alt="Image de couverture" class="">
        </div>

        <div class="flex-column justify-between flex flex-col mb-6 border rounded-lg p-4 bg-white flex flex-col gap-6 border-2 border-slate-600">
            <div>{{ $post['content'] }}</div><br>
            <div class="flex flex-row gap-4 justify-end">
                <div class="w-fit p-2 bg-red-800 text-white rounded-full self-end font-ubuntu antialiased">{{ $post->tag->name }}</div>
                <div class="w-fit p-2 bg-red-800 text-white rounded-full self-end font-ubuntu antialiased">{{ $post->subtag->name }}</div>
            </div>
        </div>
    </div>

    <div class="flex justify-center">
        <a href="{{ route('guest.dashboard') }}" title="Retourner aux articles"
            class="bg-gray-300 hover:bg-gray-200 active:border-gray-100 border-b-2 border-gray-700 rounded-full py-2 px-4">Retourner
            aux posts</a>
    </div>

</x-guest-layout>